message: one
server:
  port: 9000
spring:
  kafka:
    #properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      #ssl.endpoint.identification.algorithm:
    ssl:
      protocol: SSL
      trust-store-location: /home/asmanaeem/mykey/kafka.client.truststore.jks
      trust-store-password: changeit
      key-store-location: /home/asmanaeem/mykey/kafka.server.keystore.jks
      key-store-password: changeit
      key-password: changeit
      enabled-protocols: TLSv1.2,TLSv1.1,TLSv1
      truststore-type: PKCS12
      keystore-type: PKCS12
      client-auth: none
      sasl-mechanism: GSSAPI
      sasl-kerberos-service-name: kafka
      sasl-jaas-config: com.sun.security.auth.module.Krb5LoginModule required debug=true useKeyTab=true keyTab=\"/home/xxxxxxxxx/kafka.keytab\" principal=\"kafka/xxxxxxxxx\"
      #sasl.jaas.config=com.ibm.security.auth.module.Krb5LoginModule required useDefaultCcache=true debug=true credsType=both useKeytab=\"/home/xxxxxxxxx/kafka.keytab\" principal=\"kafka/xxxxxxxxx\";

    consumer:
      bootstrap-servers: localhost:9092
      group-id: test-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.avro.serde.deserializer.KafkaAvroDeserializer
      properties:
        isolation.level: read_committed        
        
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.avro.serde.deserializer.KafkaAvroSerializer
      transaction-id-prefix: tx.
app:
  instance-id-error: 9000
  consumer:
    props: group.instance.id=test-consumer-group-ins9000
    subscribed-to: 
      topic: test 
    publish-to:
      topic: test1    
    eos-mode: BETA    
    sub-batch-per-partition: false
  producer:
    producer-per-consumer-partition: false
    client-id: test0_client_id
    standalone:
      transaction-id-prefix: txp.
  retry: 
    topic: test.retry
    attempts: 2
    interval: 1000
  dlt: 
    topic: test.DLT
     
logging:  
  file: c:/tmp/app.log
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: INFO
    
